// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderCommon.Model;

#nullable disable

namespace OrderCommon.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20230529065753_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OrderCommon.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrdererId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SellerCommodityId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("OrdererId");

                    b.HasIndex("SellerCommodityId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderCommon.Model.Orderer", b =>
                {
                    b.Property<int>("OrdererId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("OrdererId");

                    b.ToTable("Orderers");
                });

            modelBuilder.Entity("OrderCommon.Model.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("SellerId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("OrderCommon.Model.SellerCommodity", b =>
                {
                    b.Property<int>("SellerCommodityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("SellerCommodityId");

                    b.HasIndex("SellerId");

                    b.ToTable("SellerCommodites");
                });

            modelBuilder.Entity("OrderCommon.Model.Order", b =>
                {
                    b.HasOne("OrderCommon.Model.Orderer", "Orderer")
                        .WithMany("Orders")
                        .HasForeignKey("OrdererId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderCommon.Model.SellerCommodity", "SellerCommodity")
                        .WithMany("Orders")
                        .HasForeignKey("SellerCommodityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orderer");

                    b.Navigation("SellerCommodity");
                });

            modelBuilder.Entity("OrderCommon.Model.SellerCommodity", b =>
                {
                    b.HasOne("OrderCommon.Model.Seller", "Seller")
                        .WithMany("SellerCommodities")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("OrderCommon.Model.Orderer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderCommon.Model.Seller", b =>
                {
                    b.Navigation("SellerCommodities");
                });

            modelBuilder.Entity("OrderCommon.Model.SellerCommodity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
